#!/bin/bash
#shellchecker
#coded by : Achon666ju5t - Extreme Crew
#esdnaomi[at]gmail.com
#request any tools ?
#whatsapp : +6281313208747
NC='\033[0m'
GREEN='\e[38;5;82m'
CYAN='\e[38;5;45m'
RED='\e[38;5;196m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'
ngegad(){
	for cek in $(cat $bd); do
		#edit uu=kata yang mau di grep
			uu=Uname
			ceuk=$(curl -sN $cek | grep -o $uu)
			if [ "$ceuk" = "Uname" ]; then
				echo "$cek" >> ada.txt
				printf "${GREEN}$cek -> masih ada${NC}\n"
			else
				printf "${RED}$cek -> NotFound :( \n${NC}"
			fi
		done
}
 header(){
printf "${GREEN}"
printf "     ___        __                _____ _____ _____   _       ________    \n"
printf "    /   | _____/ /_  ____  ____  / ___// ___// ___/  (_)_  __/ ____/ /_   \n"
printf "   / /| |/ ___/ __ \/ __ \/ __ \/ __ \/ __ \/ __ \  / / / / /___ \/ __/   \n"
printf "  / ___ / /__/ / / / /_/ / / / / /_/ / /_/ / /_/ / / / /_/ /___/ / /_     \n"
printf " /_/  |_\___/_/ /_/\____/_/ /_/\____/\____/\____/_/ /\__,_/_____/\__/     \n"
printf "     Mass Shell Checker By Extreme Crew        /___/ Run Dulu Baru Nanya  \n"
printf "${NC}\n"
}
clear
header
echo "_________________________________________________"
echo "File pada directory ini : "
ls
echo "_________________________________________________"
echo -n "Masukan nama file backdoor yang mau di check : "
read bd 
if [ ! -f $bd ]; then
	echo "MASUKIN NYA YANG BENER LO KIRA INI ANAL ?"
else
	sleep 4
ngegad

fi
